### ISSUE TITLE
How to debug project ?

### ISSUE THREAD

**Issue by garobcsi** [atc1441/ATC_TLSR_Paper#15]
How could i debug this project so that i could add modifications to the project.

**Comment by garobcsi** [comment]
I have no idea.

**Comment by garobcsi** [comment]
@atc1441 any help would be greatly appreciated.

**Comment by atc1441** [comment]
Hey, in general you can just compile it and use the UART TXD pin on the back to get and write your own debug outputs to make it easy to debug better :)

**Comment by garobcsi** [comment]
So if i use the uart.c and i write something out to it i could just read it w/ uart to usb ?

**Comment by garobcsi** [comment]
Also a usb to ttl would work for the flashing ?

**Comment by atc1441** [comment]
yes,
you can use the normal printf like here:
https://github.com/atc1441/ATC_TLSR_Paper/blob/main/Firmware/src/main.c#L46

so far every uart converter worked in the end

**Comment by garobcsi** [comment]
So i innit the uart and i could printf and use the uart on the back to get message. Thx for the help.

**Comment by atc1441** [comment]
Yes, but uart is already inited :)

**Comment by garobcsi** [comment]
Idk why but printf didn't work but puts void worked.
