### ISSUE TITLE
Paper_Image_Upload

### ISSUE THREAD

**Issue by garobcsi** [atc1441/ATC_TLSR_Paper#16]
Hi. I successfully flashed the e paper label and i saw u have a image uploader but there is no clear way (for me) to make my own image could you reccomed a program that could be useful for this (i saw one but i cant find it) or any other solution that could help.

**Comment by garobcsi** [comment]
i tryed everything with the img flasher nothing works even the test img is broken

**Comment by atc1441** [comment]
The best is to add a crc check for the upload and retransmit on failed ones.
It could be a problem that your device is sending the data too fast

**Comment by garobcsi** [comment]
And how don add a crc check ?

**Comment by atc1441** [comment]
Best position would be in this call https://github.com/atc1441/ATC_TLSR_Paper/blob/main/Firmware/src/epd_ble_service.c#L38
The crc value needs to be added on the sending page as well of course

**Comment by garobcsi** [comment]
On the side i send a cmd 0x00 ?

**Comment by garobcsi** [comment]
Site*

**Comment by garobcsi** [comment]
so i enabled the slower sending of the img and its clearly was slower but it still put out a broken img

**Comment by garobcsi** [comment]
So i flashed my second device and the same problem occurred.

**Comment by Bogoul** [comment]
Hi
Same for me all the pictures are like the one above.

Thank for your work.

**Comment by garobcsi** [comment]
So this is a bug... great. Thx for notifying me.

**Comment by sengelsman** [comment]
I've been trying to get the example image to display correctly on some BWR213 250x122 displays.
Finally made it work by changing the hardcoded `epd_height` and `epd_width` in `Firmware/src/epd.h` to the resolution of my display.
<edp.h> line 3
```
#define epd_height 128
#define epd_width 250
```

**Comment by garobcsi** [comment]
Oh thx

**Comment by garobcsi** [comment]
works perfectly Ty 
![image](https://user-images.githubusercontent.com/77503417/200862551-26c13ae6-9c05-445a-a02b-a5f7fb50b4b6.png)

**Comment by sengelsman** [comment]
> I've been trying to get the example image to display correctly on some BWR213 250x122 displays. Finally made it work by changing the hardcoded `epd_height` and `epd_width` in `Firmware/src/epd.h` to the resolution of my display. <edp.h> line 3
> 
> ```c
> #define epd_height 128
> #define epd_width 250
> ```

Today when flashing the firmware with this change to an epd_bwr_154 (or very close relative), the device would hang after forcing it to epd_bwr_154 and only a battery removal would make it available over the air again. After changing `epd.h` values back to the default 200x200 and re-flashing i could force the device to epd_bwr_154 and it would be stable afterwards.

**Comment by Ward11** [comment]
Hi, how do you exactly send an image to the deveice? I have no Idea how to use the image uploader, are there any tools available to create the right code to send to the ESL?

**Comment by garobcsi** [comment]
@Ward11 
Img to Hex

[Hex example](https://github.com/garobcsi/ATC_TLSR_Paper/commit/210831c778bbb150bd09c270288aa88c4ed9bc4d)

**Comment by UserXYZ** [comment]
This is pointless answer as just saying Img to Hex leads to nothing....
There are quite a few web sites where you can do conversion img2hex and hex2img, and in whatever format you give them the input image, you get useless bunch of hex bytes that represent nothing when you upload them to the tag.

To make matters worse, some of the repositories built on original do have some of the tools to manage images: stellar-L3N-etag for example has even whole web page (in Chinese though) that manages images greatly, but the code is not compatible with ATC1441 and seems to only work on one model, 296, which is not even listed on Hanshow's site.
It also has some python utilities which actually generate nothing as they are trying to import python modules that do not exist.

Mom test image that garobcsi created does work, but he never answers how did he create it - what tool or command was used, what was the input image (format, size etc).

Therefore, the original question - how does one convert own image to proper stream of hex bytes is still valid and important.

**Comment by garobcsi** [comment]
https://github.com/garobcsi/ATC_TLSR_Paper

I made my own modifications to the project. Just flash the firmware and use the modified web tool. And if you enable image mode the image will stay forever (until you change it).

**Comment by UserXYZ** [comment]
Hi garobcsi, I got a copy of your repo and flashed the code to one BWR213 I have.
It gives very similar experience to the original stellar-L3N-etag project, without the Chinese, but it also does not work with smaller BWR154 model which works just fine with original ATC1441 code.

So your version of webtools is quite useful but only for one of the tags I have.
Unfortunatelly it has a bug in image encoding/dithering - red color is replaced with black on the display, even though it is correctly shown and dithered on the web page, and the correct tag type is detected (even fixing it manually in epd.c makes no difference).

Original stellar-L3N-etag repo does not have that problem so the same BMP image I used for the test shows fine.
If I use the canvas to draw few red lines, they are also replaced with black lines in the end, so there has to be some difference between your code and original from stellar-L3N-etag repo that misses the red color.

As the smaller BWR154 is not working with your firmware, I still need to use original ATC1441 firmware for it, and then I am still presented with the same problem: how to convert input image into hex stream that is valid and can be uploaded to the tag?
What tool did you use to create your 'Mom' picture here: https://github.com/garobcsi/ATC_TLSR_Paper/commit/210831c778bbb150bd09c270288aa88c4ed9bc4d

**Comment by garobcsi** [comment]
Btw for the red and withe and black issue 
![image](https://github.com/atc1441/ATC_TLSR_Paper/assets/77503417/c1db4f77-81ed-4ae6-a087-43a00eae0d17)
Edit: i think i just removed the option to select different colors. I will fix it when i have time.
~~u can just change the algorithm.~~
And the red output only works if it using the 296 mode forced. (Some models already use it forced)
- u can find the mode witch useing on the first clock mode (the second clock mode boots by default)

For the Hex convertion i used this on windows: https://www.waveshare.com/wiki/File:Image2Lcd.7z
- Set 250 128 resulution
- export it as .c
- ignore first line bc not as same length as the others
- remove 0x\<data\>,      (keep the data)
- and you can use it on the image flasher (red image not supported on the old flasher)

On linux i used a tool but i already forgot what i used.

Btw also you cloud try:
- open gimp
- set resolotion to 250 128
- set a Dithering algorithm
- set it black and white
- read the hex bytes out of the image (many linux tools exits)

**Comment by UserXYZ** [comment]
Thanks for the reply - could you explain what field shows the mode when choosing clock type 1?
For example, my BWR213 shows the top line with this: "ESL_32A95C BWR213 BLE T"
Is it this "BLE T"?

Also, how does one force the mode for 296 model? Is it limitation of the software, firmware or the modules themselves?

**Comment by garobcsi** [comment]
BLE T
BLE F

BLE: Bluetooth Low Energy
Ture and False
.
In the web tools the forcing option is possible but not implemented in the web tool.
Also you could modify the firmware to default to 296

@![20240102_232841.jpg](https://github.com/atc1441/ATC_TLSR_Paper/assets/77503417/7c75421d-7087-4022-916e-991b458d9809)

Also in this file 
https://github.com/garobcsi/ATC_TLSR_Paper/blob/main/Firmware/src/epd.c
You clould just modify the if cases to force 296 firmweare.
Btw running diffrent model code on a diffrent model could brick it. (you have to reflash it truh the uart port again if happens)

**Comment by Ward11** [comment]
> https://github.com/garobcsi/ATC_TLSR_Paper
> 
> I made my own modifications to the project. Just flash the firmware and use the modified web tool. And if you enable image mode the image will stay forever (until you change it).

Great, I will try it out :)
Here are some results from fiddling around last summer;
![IMG_20240103_101206191](https://github.com/atc1441/ATC_TLSR_Paper/assets/23584519/291c6e4e-9180-4cbe-9885-765d048cea36)

**Comment by UserXYZ** [comment]
Hi @Ward11 , I see in your pictures that you got 3 colors displayed....which device model it is then? 213BWR or 296BWR?
I tried to use stellar-L3N-etag firmware on 213BWR, and then used @garobcsi web tools to control it - it does work, I can even get 3 colors, but the display still resizes itself to the dimensions of 296 so screen is wider than it is for my 213 tags.

So, if you're also having 213BWR, please share how you got the firmware to work properly.

**Comment by UserXYZ** [comment]
BTW @garobcsi , I modified these two lines in epd.c to try and force 296 model:
`RAM uint8_t epd_model = 5; // 0 = Undetected, 1 = BW213, 2 = BWR213, 3 = BWR154, 4 = BW213ICE, 5 BWR296`
and
`epd_model = 5`

Did not touch if-then-else parts as they are triggered only if previous is set to auto-detect.

And it seems to work! Yeeeyyyy...

When setting the mode to clock1, it still shows as BWR296, but it sizes everything to the size of BWR213 (as defined in epd.h).
When switching to picture mode, I can upload any picture now and with BWR dithering, I finally get all 3 colors on the correct size.

So, I think it's the best I can get for now - it's just that I'd like to know is this modification of epd.c (and epd.h) correct way to go....wouldn't want my success to be a fluke, heh...

Cheers.

**Comment by garobcsi** [comment]
If you modify the screen size in epd.h that (you should) you also have to modify the web tool too bc it wont be the same size as your screen.
For the autodetect just remove it ?! Idk

**Comment by garobcsi** [comment]
Also the web tool is modified for my firmweare.
For other firmweares im not doing compatibilities
