### ISSUE TITLE
cppcheck warning

### ISSUE THREAD

**Issue by holgerlembke** [atc1441/ATC_TLSR_Paper#3]
https://github.com/atc1441/ATC_TLSR_Paper/blob/5a85959211960cedfa7b98291301c23ef63a250e/Firmware/src/obd.inl#L2314

```
    iPitch = pOBD->width;

    if (pDestination == NULL || pOBD == NULL || pOBD->ucScreen == NULL)
        return -1;
```
Looks fishy to me, too. :-)

**Comment by bitbank2** [comment]
Not currently used or important, but I pushed a fix https://github.com/atc1441/ATC_TLSR_Paper/commit/26ff2c5108dd397a39a707b31ec240d938b1d1d5
